baseurl = "https://rafaelzomer.github.io/blog/"
copyright = "Todos os direitos reservados"
disqusshortname = "rafaelzomer"
languagecode = "pt-BR"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-casper"
title = "rafaelzomer"

[params]
author = "Rafael Zomer Antunes"
authorlocation = "Brazil"
authorbio = "Fullstack Developer"
cover = "images/cover.jpg"
description = "Tutoriais sobre programação"
githubName = "rafaelzomer"
googleAnalyticsUserID = "UA-47115458-4"
hideHUGOSupport = false
logo = "https://github.com/rafaelzomer.png?size=200"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"